load("@rules_python//python:pip.bzl", "compile_pip_requirements")

compile_pip_requirements(
    name = "sim_py_req_compile",
    src = "requirements.in",
    requirements_txt = "requirements.txt",
)
