#ifndef APPLICATIONS_APPLICATIONS_PARAM
#define APPLICATIONS_APPLICATIONS_PARAM

#define T_CARCONTROL_PUB 10  // ms
#define QS_CARCONTROL_PUB 5  // queue size
#define T_PLANNING_PUB 100   // ms

#endif  // APPLICATIONS_APPLICATIONS_PARAM
