load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "lookup_table_tests",
    srcs = ["lookup_table_tests.cpp"],
    deps = [
        "//core/support/utils",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
