// proudly AI-generated, human-reviewed
// Future: auto-generated by a Bazel rule from the IDL.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <string>

#include "ChannelMessage.hpp"

PYBIND11_MODULE(channel_message_py, module) {
  module.doc() = "ChannelMessage IDL type — pybind11 binding";
  pybind11::class_<ChannelMessage>(module, "ChannelMessage")
      .def(pybind11::init<>())
      .def_property(
          "content",
          [](const ChannelMessage& m) { return m.content(); },
          [](ChannelMessage& m, const std::string& v) { m.content(v); })
      .def_property(
          "counter",
          [](const ChannelMessage& m) { return m.counter(); },
          [](ChannelMessage& m, uint32_t v) { m.counter(v); })
      .def("__repr__", [](const ChannelMessage& m) {
        return "ChannelMessage(content='" + m.content() +
               "', counter=" + std::to_string(m.counter()) + ")";
      });
}
