// proudly AI-generated, human-reviewed
// Future: auto-generated by a Bazel rule from ports YAML + IDL.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <vector>

#include "ChannelMessage.hpp"
#include "chatter_ports_publications.hpp"
#include "chatter_ports_subscriptions.hpp"
#include "simulation/py_dds_talker/py_dds_bridge.hpp"

using Pub = cpp::Publications;
using Sub = cpp::Subscriptions;

/// pub/sub are inverted wrt the cpp talker node
using Bridge = PyDDSBridge<Pub, Sub>;

PYBIND11_MODULE(chatter_bridge_py, module) {
  module.doc() = "PyDDSBridge instantiation for the chatter test node.";

  // Ensure ChannelMessage is registered in pybind11's type table before
  // binding methods that accept or return it.
  pybind11::module_::import("channel_message_py");

  pybind11::class_<Bridge>(module, "PyDDSBridge")
      .def(pybind11::init<const std::string&>(),
           pybind11::arg("participant_name"))
      .def("init", &Bridge::Init)
      .def("participant_name", &Bridge::ParticipantName)
      .def("fill_inputs", &Bridge::FillInputs)
      .def("flush_outputs", &Bridge::FlushOutputs)
      .def("get_inputs",
           [](Bridge& self) {
             return self.GetInputs<cpp::kChannelATopicName>();
           })
      .def(
          "push_output",
          [](Bridge& self, ChannelMessage msg) {
            self.PushOutput<cpp::kChannelBTopicName>(std::move(msg));
          },
          pybind11::arg("message"));
}
