// proudly AI-generated, human-reviewed
// Future: auto-generated by a Bazel rule from the IDL.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <string>
#include <vector>

#include "ChannelMessage.hpp"
#include "ChannelMessagePubSubTypes.hpp"
#include "chatter_ports_publications.hpp"
#include "chatter_ports_subscriptions.hpp"
#include "simulation/py_dds_talker/py_dds_bridge.hpp"
// #include "core/communication/dds_publisher.hpp"
// #include "core/communication/dds_subscriber.hpp"

using Pub = cpp::Publications;
using Sub = cpp::Subscriptions;

/// we're inverting the pub and sub wtr to cpp talker node
using OPont = PyDDSBridge<Pub, Sub>;

PYBIND11_MODULE(py_mock_channel, module) {
  module.doc() = "pybind  pybind11 binding";

  pybind11::class_<ChannelMessage>(module, "ChannelMessage")
      .def(pybind11::init<>())
      .def_property(
          "content", [](const ChannelMessage& m) { return m.content(); },
          [](ChannelMessage& m, const std::string& v) { m.content(v); })
      .def_property(
          "counter", [](const ChannelMessage& m) { return m.counter(); },
          [](ChannelMessage& m, uint32_t v) { m.counter(v); })
      .def("__repr__", [](const ChannelMessage& m) {
        return "ChannelMessage(content='" + m.content() +
               "', counter=" + std::to_string(m.counter()) + ")";
      });

  pybind11::class_<OPont>(module, "PyDDSBridge")
      .def(pybind11::init<const std::string&>(),
           pybind11::arg("participant_name"))
      .def("init", &OPont::Init)
      .def("participant_name", &OPont::ParticipantName)
      .def("fill_inputs", &OPont::FillInputs)
      .def("flush_outputs", &OPont::FlushOutputs)
      .def(
          "get_inputs",
          [](OPont& self) { return self.GetInputs<cpp::kChannelATopicName>(); })
      .def(
          "push_output",
          [](OPont& self, ChannelMessage msg) {
            self.PushOutput<cpp::kChannelBTopicName>(std::move(msg));
          },
          pybind11::arg("message"));
}
