load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//core:__subpackages__"])

cc_library(
    name = "utils",
    hdrs = [
        "black_magic_tuple_merger.hpp",
        "lookup_table.hpp",
        "size_constrained_queue.hpp",
    ],
)
