model: ai.models.agent.PPOLightningAgent
loss: ai.loss.ppo_loss.PPOLoss
trainer: ai.training_algorithms.ppo_train.ppo_train
exp_name: default
devices: 2
accelerator: cpu
strategy: ddp
seed: 42
cuda: false
player_on_gpu: false
torch_deterministic: true
num_envs: 2
env_id: Ant-v5
env_specs: {xml_file: "./simulation/robot_model/spot.xml",
            render_mode: "rgb_array",
            forward_reward_weight: 1,
            ctrl_cost_weight: 0.05,
            contact_cost_weight: 5e-4,
            healthy_reward: 1,
            main_body: 1,
            healthy_z_range: [0.195, 0.75],
            include_cfrc_ext_in_observation: True,
            exclude_current_positions_from_observation: False,
            reset_noise_scale: 0.1,
            frame_skip: 25,
            max_episode_steps: 1000}
share_data: false
per_rank_batch_size: 64
num_steps: 128
capture_video: true
total_timesteps: 65536
learning_rate: 0.001
anneal_lr: false
gamma: 0.99
gae_lambda: 0.95
update_epochs: 10
activation_function: relu
ortho_init: false
normalize_advantages: false
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.0
vf_coef: 1.0
max_grad_norm: 0.5