model: ai.models.ppo_agent.PPOAgent
loss: ai.loss.ppo_loss.PPOLoss
trainer: ai.trainers.ppo_train.ppo_train
exp_name: default
devices: 2
accelerator: cpu
strategy: ddp
seed: 42
cuda: false
player_on_gpu: false
torch_deterministic: true
num_envs: 2
env_id: CartPole-v1
env_specs: {render_mode: "rgb_array",}
share_data: false
per_rank_batch_size: 64
num_steps: 128
capture_video: true
total_timesteps: 65536
learning_rate: 0.001
anneal_lr: false
gamma: 0.99
gae_lambda: 0.95
update_epochs: 10
activation_function: relu
ortho_init: false
normalize_advantages: false
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.0
vf_coef: 1.0
max_grad_norm: 0.5