load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "py_dds_bridge",
    hdrs = ["py_dds_bridge.hpp"],
    deps = [
        "//core/lifecycle:dds",
    ],
)

