name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: ./.github/actions/setup_environment
      - uses: MockaSort-Studio/actions/.github/actions/build-bazel@main
        with:
          targets: //...
          config: main
          build_buddy_key: ${{ secrets.BUILD_BUDDY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
