name: build-and-test

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.trigger.outputs.triggered }}
      head-sha: ${{ steps.trigger.outputs.head-sha }}
      check-run-id: ${{ steps.trigger.outputs.check-run-id }}
    steps:
      - uses: MockaSort-Studio/actions/.github/actions/pr-comment-trigger-start-checks@main
        id: trigger
        with:
          trigger-phrase: ":pig_nose:"
          check-name: build-and-test
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: trigger
    if: needs.trigger.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.trigger.outputs.head-sha }}
          lfs: true
      - uses: ./.github/actions/setup_environment
      - uses: MockaSort-Studio/actions/.github/actions/build-bazel@main
        with:
          targets: //...
          config: ci
          build_buddy_key: ${{ secrets.BUILD_BUDDY_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  finish:
    needs: [trigger, build]
    if: always() && needs.trigger.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: MockaSort-Studio/actions/.github/actions/pr-comment-trigger-finish-checks@main
        with:
          check-run-id: ${{ needs.trigger.outputs.check-run-id }}
          status: ${{ needs.build.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
