name: docs-deploy
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'zensical.toml'
      - '.github/workflows/docs_deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: MockaSort-Studio/actions/.github/workflows/docs-deploy.yml@main
    with:
      config-file: zensical.toml
